# print("Hello from lesson 1")

######### The below is the code required for task 2a ##########
# print("1")
# print("2")
# print("3")
# print("4")
# print("5")
# print("6")
# print("7")
# print("8")
# print("9")
# print("10")
# print("11")
# print("12")
# print("13")
# print("14")
# print("15")
# print("16")
# print("17")
# print("18")
# print("19")
# print("20")
# print("21")
# print("22")
# print("23")
# print("24")
# print("25")
# print("26")
# print("27")
# print("28")
# print("29")
# print("30")
# print("31")

# print("January")
# print("February")
# print("March")
# print("April")
# print("May")
# print("June")
# print("July")
# print("August")
# print("September")
# print("October")
# print("November")
# print("December")

# print("2020")
# print("2021")
# print("2022")
# print("2023")
# print("2024")
# print("2025")
# print("2026")
# print("2027")
# print("2028")
# print("2029")
# print("2030")

############## Below is the code for task 2b ##############
# print("1")
# print("2")
# print("3")
# print("4")
# print("5")
# print("6")
# print("7")
# print("8")
# print("9")
# print("10")
# print("11")
# print("12")
# print("13")
# print("14")
# print("15")
# print("16")
# print("17")
# print("18")
# print("19")
# print("20")
# print("21")
# print("22")
# print("23")
# print("24")
# print("25")
# print("26")
# print("27")
# print("28")
# print("29")
# print("30")
# print("31")

# print("January")
# print("February")
# print("March")
# print("April")
# print("May")
# print("June")
# print("July")
# print("August")
# print("September")
# print("October")
# print("November")
# print("December")

# print("2020")
# print("2021")
# print("2022")
# print("2023")
# print("2024")
# print("2025")
# print("2026")
# print("2027")
# print("2028")
# print("2029")
# print("2030")

# print("Hello world")
# print("My favourite food is chicken rice")
# print("My birthday is on 5 April 2012")

# print("My name is Marc Tay")
# print("I am 12 years old")
# print("I attend Maris Stella High School")
# print("If I had $2,000, I would buy some items in the games that I play ")

# print("First, I would fold my blanket")
# print("Next, I would wash my face and go to the toilet")
# print("After that, I would eat my breakfast")
# print("Thereafter, I would brush my teeth")
# print("Straight after, I would dress up in my school uniform")
# print("Lastly, I would take my school bag and leave for school")

print("Hello and how are you?")

print("What is wrong with this")

print("Why is this not working?")

print("Why is this not working?")